# Generated by Django 3.2.9 on 2022-08-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_areaofspecialization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofspecialization',
            name='more_info',
            field=models.TextField(blank=True),
        ),
    ]
