# Generated by Django 3.2.9 on 2022-08-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findtalentrequest',
            name='area_of_specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization'),
        ),
        migrations.AlterField(
            model_name='hiretalentrequest',
            name='area_of_need',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='area_of_specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='area_of_specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization'),
        ),
    ]
